### ISSUE TITLE
How is the treatment assigned?

### ISSUE THREAD

**Issue by xiongzhp** [jsyoon0823/GANITE#1]
Hi Yoon,
I just couldn't understand how the treatment is assigned like this. Is there any rationale for it? Thanks!
https://github.com/jsyoon0823/GANITE/blob/e2997317d5e8699d6fd56e704cae35890f5599c8/data_loading.py#L54-L62

**Comment by jsyoon0823** [comment]
No. There is no rationale for this treatment assignment.
We just want to make a selection bias for treatment assignment; therefore, we first randomly select the coefficient and then assign the treatment through these equations.
In that case, the treatment assignments have selection bias (even though the bias itself does not have any rationales).
