### ISSUE TITLE
Is PEHE correctly calculated?

### ISSUE THREAD

**Issue by alex-stoica** [jsyoon0823/GANITE#2]
In metrics.py, line 37, PEHE is calculated
`PEHE_val = np.mean( np.abs( (y[:,1] - y[:,0]) - (y_hat[:,1] - y_hat[:,0]) ))`
However, in the paper (https://openreview.net/forum?id=ByKWUeWA-) it seems that PEHE depdends on the **squared** difference between the predicted ITE and true ITE, not the **absolute** difference. 
Shouldn't it be replaced with 
`np.mean(np.square((y[:,1] - y[:,0]) - (y_hat[:,1] - y_hat[:,0])))`
?

**Comment by jsyoon0823** [comment]
Thank you for raising this issue.
As we know, both MAE and MSE are good ways to measure the performances.
This is also applicable in PEHE as well. Thus, in our codebase, we use np.abs instead of np.square. 
Sorry for the confusion about the difference between paper and code implementation.
