### ISSUE TITLE
A misunderstood in the code by my own, my apology for the confusion and I deeply appreciate the author's patience and clarification.

### ISSUE THREAD

**Issue by uqhwen2** [jsyoon0823/GANITE#4]

**Comment by jsyoon0823** [comment]
Sorry for the inconvenience.
Note that we need to do hyper-parameter tuning for each dataset separately.
We have no plan to update this codebase for Jobs and IHDP data until now.

**Comment by WEN-Hechuan** [comment]
Did you say "**we need to do hyper-parameter tuning for each dataset separately**" for the 100 random splits? That's definitely not computationally efficient at all and that's not the way other paper using. We generally require a form that has best performance among 100 times experiments. I notice that you provided one set of the **optiaml hyper-parameters** in the paper **Appendix** for Twin (binary) dataset, which defaultly means that's a general solution for this 100 random splits,  and I used that optiaml parameters and definitely cannot reproduce your claimed "optimal results"

I'm being very serious here, my previous thesis supervior told be never claimed something you don't have support for. I can see such a inresponsible atitude here. It's not simply "**Sorry for the inconvenience**." can resolve!

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.
And first, please calm down. This is a public repository and this should not be used as blaming something.

I have not said that we need to do hyper-parameter tuning for each dataset for 100 random splits.
I just said that we need different hyper-parameters for different dataset.

Also, please see the more recent GANITE codebase here (https://github.com/vanderschaarlab/mlforhealthlabpub/tree/main/alg/ganite).
